// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: downloader.proto

package downloader

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//Solicitamos ver los libros almacenados en el NameNode
type Solicitud_VerLibros struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Solicitud_VerLibros) Reset() {
	*x = Solicitud_VerLibros{}
	if protoimpl.UnsafeEnabled {
		mi := &file_downloader_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Solicitud_VerLibros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solicitud_VerLibros) ProtoMessage() {}

func (x *Solicitud_VerLibros) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solicitud_VerLibros.ProtoReflect.Descriptor instead.
func (*Solicitud_VerLibros) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{0}
}

//respuesta de los libros
type Respuesta_VerLibros struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LibrosDisponibles string `protobuf:"bytes,1,opt,name=librosDisponibles,proto3" json:"librosDisponibles,omitempty"`
}

func (x *Respuesta_VerLibros) Reset() {
	*x = Respuesta_VerLibros{}
	if protoimpl.UnsafeEnabled {
		mi := &file_downloader_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta_VerLibros) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta_VerLibros) ProtoMessage() {}

func (x *Respuesta_VerLibros) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta_VerLibros.ProtoReflect.Descriptor instead.
func (*Respuesta_VerLibros) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta_VerLibros) GetLibrosDisponibles() string {
	if x != nil {
		return x.LibrosDisponibles
	}
	return ""
}

//se solicita la ubicacion chunks de los libros
type Solicitud_Ubicaciones struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreLibro string `protobuf:"bytes,1,opt,name=nombreLibro,proto3" json:"nombreLibro,omitempty"`
}

func (x *Solicitud_Ubicaciones) Reset() {
	*x = Solicitud_Ubicaciones{}
	if protoimpl.UnsafeEnabled {
		mi := &file_downloader_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Solicitud_Ubicaciones) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solicitud_Ubicaciones) ProtoMessage() {}

func (x *Solicitud_Ubicaciones) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solicitud_Ubicaciones.ProtoReflect.Descriptor instead.
func (*Solicitud_Ubicaciones) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{2}
}

func (x *Solicitud_Ubicaciones) GetNombreLibro() string {
	if x != nil {
		return x.NombreLibro
	}
	return ""
}

//respuesta de la ubicacion por parte del NameNode
type Respuesta_Ubicaciones struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ubicaciones string `protobuf:"bytes,1,opt,name=ubicaciones,proto3" json:"ubicaciones,omitempty"`
}

func (x *Respuesta_Ubicaciones) Reset() {
	*x = Respuesta_Ubicaciones{}
	if protoimpl.UnsafeEnabled {
		mi := &file_downloader_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta_Ubicaciones) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta_Ubicaciones) ProtoMessage() {}

func (x *Respuesta_Ubicaciones) ProtoReflect() protoreflect.Message {
	mi := &file_downloader_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta_Ubicaciones.ProtoReflect.Descriptor instead.
func (*Respuesta_Ubicaciones) Descriptor() ([]byte, []int) {
	return file_downloader_proto_rawDescGZIP(), []int{3}
}

func (x *Respuesta_Ubicaciones) GetUbicaciones() string {
	if x != nil {
		return x.Ubicaciones
	}
	return ""
}

var File_downloader_proto protoreflect.FileDescriptor

var file_downloader_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x22, 0x15,
	0x0a, 0x13, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x5f, 0x56, 0x65, 0x72, 0x4c,
	0x69, 0x62, 0x72, 0x6f, 0x73, 0x22, 0x43, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x5f, 0x56, 0x65, 0x72, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x73, 0x12, 0x2c, 0x0a, 0x11,
	0x6c, 0x69, 0x62, 0x72, 0x6f, 0x73, 0x44, 0x69, 0x73, 0x70, 0x6f, 0x6e, 0x69, 0x62, 0x6c, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6c, 0x69, 0x62, 0x72, 0x6f, 0x73, 0x44,
	0x69, 0x73, 0x70, 0x6f, 0x6e, 0x69, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x15, 0x53, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x5f, 0x55, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f,
	0x6e, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4c, 0x69, 0x62,
	0x72, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65,
	0x4c, 0x69, 0x62, 0x72, 0x6f, 0x22, 0x39, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x5f, 0x55, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x20,
	0x0a, 0x0b, 0x75, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73,
	0x32, 0xb7, 0x01, 0x0a, 0x0a, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x4f, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x73, 0x12, 0x1f, 0x2e, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69,
	0x74, 0x75, 0x64, 0x5f, 0x56, 0x65, 0x72, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x73, 0x1a, 0x1f, 0x2e,
	0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x5f, 0x56, 0x65, 0x72, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x73, 0x22, 0x00,
	0x12, 0x58, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x55, 0x62, 0x69, 0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e,
	0x65, 0x73, 0x12, 0x21, 0x2e, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e,
	0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x5f, 0x55, 0x62, 0x69, 0x63, 0x61, 0x63,
	0x69, 0x6f, 0x6e, 0x65, 0x73, 0x1a, 0x21, 0x2e, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x5f, 0x55, 0x62, 0x69,
	0x63, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_downloader_proto_rawDescOnce sync.Once
	file_downloader_proto_rawDescData = file_downloader_proto_rawDesc
)

func file_downloader_proto_rawDescGZIP() []byte {
	file_downloader_proto_rawDescOnce.Do(func() {
		file_downloader_proto_rawDescData = protoimpl.X.CompressGZIP(file_downloader_proto_rawDescData)
	})
	return file_downloader_proto_rawDescData
}

var file_downloader_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_downloader_proto_goTypes = []interface{}{
	(*Solicitud_VerLibros)(nil),   // 0: downloader.Solicitud_VerLibros
	(*Respuesta_VerLibros)(nil),   // 1: downloader.Respuesta_VerLibros
	(*Solicitud_Ubicaciones)(nil), // 2: downloader.Solicitud_Ubicaciones
	(*Respuesta_Ubicaciones)(nil), // 3: downloader.Respuesta_Ubicaciones
}
var file_downloader_proto_depIdxs = []int32{
	0, // 0: downloader.Downloader.VerLibros:input_type -> downloader.Solicitud_VerLibros
	2, // 1: downloader.Downloader.VerUbicaciones:input_type -> downloader.Solicitud_Ubicaciones
	1, // 2: downloader.Downloader.VerLibros:output_type -> downloader.Respuesta_VerLibros
	3, // 3: downloader.Downloader.VerUbicaciones:output_type -> downloader.Respuesta_Ubicaciones
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_downloader_proto_init() }
func file_downloader_proto_init() {
	if File_downloader_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_downloader_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Solicitud_VerLibros); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_downloader_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta_VerLibros); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_downloader_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Solicitud_Ubicaciones); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_downloader_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta_Ubicaciones); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_downloader_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_downloader_proto_goTypes,
		DependencyIndexes: file_downloader_proto_depIdxs,
		MessageInfos:      file_downloader_proto_msgTypes,
	}.Build()
	File_downloader_proto = out.File
	file_downloader_proto_rawDesc = nil
	file_downloader_proto_goTypes = nil
	file_downloader_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DownloaderClient is the client API for Downloader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DownloaderClient interface {
	VerLibros(ctx context.Context, in *Solicitud_VerLibros, opts ...grpc.CallOption) (*Respuesta_VerLibros, error)
	VerUbicaciones(ctx context.Context, in *Solicitud_Ubicaciones, opts ...grpc.CallOption) (*Respuesta_Ubicaciones, error)
}

type downloaderClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloaderClient(cc grpc.ClientConnInterface) DownloaderClient {
	return &downloaderClient{cc}
}

func (c *downloaderClient) VerLibros(ctx context.Context, in *Solicitud_VerLibros, opts ...grpc.CallOption) (*Respuesta_VerLibros, error) {
	out := new(Respuesta_VerLibros)
	err := c.cc.Invoke(ctx, "/downloader.Downloader/VerLibros", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloaderClient) VerUbicaciones(ctx context.Context, in *Solicitud_Ubicaciones, opts ...grpc.CallOption) (*Respuesta_Ubicaciones, error) {
	out := new(Respuesta_Ubicaciones)
	err := c.cc.Invoke(ctx, "/downloader.Downloader/VerUbicaciones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DownloaderServer is the server API for Downloader service.
type DownloaderServer interface {
	VerLibros(context.Context, *Solicitud_VerLibros) (*Respuesta_VerLibros, error)
	VerUbicaciones(context.Context, *Solicitud_Ubicaciones) (*Respuesta_Ubicaciones, error)
}

// UnimplementedDownloaderServer can be embedded to have forward compatible implementations.
type UnimplementedDownloaderServer struct {
}

func (*UnimplementedDownloaderServer) VerLibros(context.Context, *Solicitud_VerLibros) (*Respuesta_VerLibros, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerLibros not implemented")
}
func (*UnimplementedDownloaderServer) VerUbicaciones(context.Context, *Solicitud_Ubicaciones) (*Respuesta_Ubicaciones, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerUbicaciones not implemented")
}

func RegisterDownloaderServer(s *grpc.Server, srv DownloaderServer) {
	s.RegisterService(&_Downloader_serviceDesc, srv)
}

func _Downloader_VerLibros_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solicitud_VerLibros)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloaderServer).VerLibros(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/downloader.Downloader/VerLibros",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloaderServer).VerLibros(ctx, req.(*Solicitud_VerLibros))
	}
	return interceptor(ctx, in, info, handler)
}

func _Downloader_VerUbicaciones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solicitud_Ubicaciones)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloaderServer).VerUbicaciones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/downloader.Downloader/VerUbicaciones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloaderServer).VerUbicaciones(ctx, req.(*Solicitud_Ubicaciones))
	}
	return interceptor(ctx, in, info, handler)
}

var _Downloader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "downloader.Downloader",
	HandlerType: (*DownloaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerLibros",
			Handler:    _Downloader_VerLibros_Handler,
		},
		{
			MethodName: "VerUbicaciones",
			Handler:    _Downloader_VerUbicaciones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "downloader.proto",
}
