// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: uploader.proto

package uploader

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//solicita subir un libro
type Solicitud_SubirLibro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk              []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Id                 int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	NombreLibro        string `protobuf:"bytes,3,opt,name=nombre_libro,json=nombreLibro,proto3" json:"nombre_libro,omitempty"`
	Cantidad           int32  `protobuf:"varint,4,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	TipoExclusionMutua string `protobuf:"bytes,5,opt,name=tipoExclusionMutua,proto3" json:"tipoExclusionMutua,omitempty"`
}

func (x *Solicitud_SubirLibro) Reset() {
	*x = Solicitud_SubirLibro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uploader_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Solicitud_SubirLibro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solicitud_SubirLibro) ProtoMessage() {}

func (x *Solicitud_SubirLibro) ProtoReflect() protoreflect.Message {
	mi := &file_uploader_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solicitud_SubirLibro.ProtoReflect.Descriptor instead.
func (*Solicitud_SubirLibro) Descriptor() ([]byte, []int) {
	return file_uploader_proto_rawDescGZIP(), []int{0}
}

func (x *Solicitud_SubirLibro) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *Solicitud_SubirLibro) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Solicitud_SubirLibro) GetNombreLibro() string {
	if x != nil {
		return x.NombreLibro
	}
	return ""
}

func (x *Solicitud_SubirLibro) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

func (x *Solicitud_SubirLibro) GetTipoExclusionMutua() string {
	if x != nil {
		return x.TipoExclusionMutua
	}
	return ""
}

//respuesta del dataNode
type Respuesta_SubirLibro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta int32 `protobuf:"varint,1,opt,name=respuesta,proto3" json:"respuesta,omitempty"`
}

func (x *Respuesta_SubirLibro) Reset() {
	*x = Respuesta_SubirLibro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uploader_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta_SubirLibro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta_SubirLibro) ProtoMessage() {}

func (x *Respuesta_SubirLibro) ProtoReflect() protoreflect.Message {
	mi := &file_uploader_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta_SubirLibro.ProtoReflect.Descriptor instead.
func (*Respuesta_SubirLibro) Descriptor() ([]byte, []int) {
	return file_uploader_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta_SubirLibro) GetRespuesta() int32 {
	if x != nil {
		return x.Respuesta
	}
	return 0
}

var File_uploader_proto protoreflect.FileDescriptor

var file_uploader_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x22, 0xab, 0x01, 0x0a, 0x14, 0x53,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x5f, 0x53, 0x75, 0x62, 0x69, 0x72, 0x4c, 0x69,
	0x62, 0x72, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x5f, 0x6c, 0x69, 0x62, 0x72, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x63, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x74, 0x69, 0x70, 0x6f,
	0x45, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x75, 0x74, 0x75, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x74, 0x69, 0x70, 0x6f, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73,
	0x69, 0x6f, 0x6e, 0x4d, 0x75, 0x74, 0x75, 0x61, 0x22, 0x34, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x5f, 0x53, 0x75, 0x62, 0x69, 0x72, 0x4c, 0x69, 0x62, 0x72, 0x6f,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x32, 0x5a,
	0x0a, 0x08, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x12, 0x4e, 0x0a, 0x0a, 0x53, 0x75,
	0x62, 0x69, 0x72, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x12, 0x1e, 0x2e, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x65, 0x72, 0x2e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x5f, 0x53, 0x75,
	0x62, 0x69, 0x72, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x1a, 0x1e, 0x2e, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x5f, 0x53, 0x75,
	0x62, 0x69, 0x72, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_uploader_proto_rawDescOnce sync.Once
	file_uploader_proto_rawDescData = file_uploader_proto_rawDesc
)

func file_uploader_proto_rawDescGZIP() []byte {
	file_uploader_proto_rawDescOnce.Do(func() {
		file_uploader_proto_rawDescData = protoimpl.X.CompressGZIP(file_uploader_proto_rawDescData)
	})
	return file_uploader_proto_rawDescData
}

var file_uploader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_uploader_proto_goTypes = []interface{}{
	(*Solicitud_SubirLibro)(nil), // 0: uploader.Solicitud_SubirLibro
	(*Respuesta_SubirLibro)(nil), // 1: uploader.Respuesta_SubirLibro
}
var file_uploader_proto_depIdxs = []int32{
	0, // 0: uploader.Uploader.SubirLibro:input_type -> uploader.Solicitud_SubirLibro
	1, // 1: uploader.Uploader.SubirLibro:output_type -> uploader.Respuesta_SubirLibro
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_uploader_proto_init() }
func file_uploader_proto_init() {
	if File_uploader_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uploader_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Solicitud_SubirLibro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uploader_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta_SubirLibro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uploader_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_uploader_proto_goTypes,
		DependencyIndexes: file_uploader_proto_depIdxs,
		MessageInfos:      file_uploader_proto_msgTypes,
	}.Build()
	File_uploader_proto = out.File
	file_uploader_proto_rawDesc = nil
	file_uploader_proto_goTypes = nil
	file_uploader_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UploaderClient is the client API for Uploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UploaderClient interface {
	SubirLibro(ctx context.Context, in *Solicitud_SubirLibro, opts ...grpc.CallOption) (*Respuesta_SubirLibro, error)
}

type uploaderClient struct {
	cc grpc.ClientConnInterface
}

func NewUploaderClient(cc grpc.ClientConnInterface) UploaderClient {
	return &uploaderClient{cc}
}

func (c *uploaderClient) SubirLibro(ctx context.Context, in *Solicitud_SubirLibro, opts ...grpc.CallOption) (*Respuesta_SubirLibro, error) {
	out := new(Respuesta_SubirLibro)
	err := c.cc.Invoke(ctx, "/uploader.Uploader/SubirLibro", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploaderServer is the server API for Uploader service.
type UploaderServer interface {
	SubirLibro(context.Context, *Solicitud_SubirLibro) (*Respuesta_SubirLibro, error)
}

// UnimplementedUploaderServer can be embedded to have forward compatible implementations.
type UnimplementedUploaderServer struct {
}

func (*UnimplementedUploaderServer) SubirLibro(context.Context, *Solicitud_SubirLibro) (*Respuesta_SubirLibro, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubirLibro not implemented")
}

func RegisterUploaderServer(s *grpc.Server, srv UploaderServer) {
	s.RegisterService(&_Uploader_serviceDesc, srv)
}

func _Uploader_SubirLibro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solicitud_SubirLibro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploaderServer).SubirLibro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uploader.Uploader/SubirLibro",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploaderServer).SubirLibro(ctx, req.(*Solicitud_SubirLibro))
	}
	return interceptor(ctx, in, info, handler)
}

var _Uploader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uploader.Uploader",
	HandlerType: (*UploaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubirLibro",
			Handler:    _Uploader_SubirLibro_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uploader.proto",
}
