// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: propu.proto

package propu

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Propuesta_Generada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListaPropuesta []int32 `protobuf:"varint,1,rep,packed,name=ListaPropuesta,proto3" json:"ListaPropuesta,omitempty"`
}

func (x *Propuesta_Generada) Reset() {
	*x = Propuesta_Generada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_propu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Propuesta_Generada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Propuesta_Generada) ProtoMessage() {}

func (x *Propuesta_Generada) ProtoReflect() protoreflect.Message {
	mi := &file_propu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Propuesta_Generada.ProtoReflect.Descriptor instead.
func (*Propuesta_Generada) Descriptor() ([]byte, []int) {
	return file_propu_proto_rawDescGZIP(), []int{0}
}

func (x *Propuesta_Generada) GetListaPropuesta() []int32 {
	if x != nil {
		return x.ListaPropuesta
	}
	return nil
}

type Respuesta_Propuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respuesta string `protobuf:"bytes,1,opt,name=respuesta,proto3" json:"respuesta,omitempty"`
}

func (x *Respuesta_Propuesta) Reset() {
	*x = Respuesta_Propuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_propu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta_Propuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta_Propuesta) ProtoMessage() {}

func (x *Respuesta_Propuesta) ProtoReflect() protoreflect.Message {
	mi := &file_propu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta_Propuesta.ProtoReflect.Descriptor instead.
func (*Respuesta_Propuesta) Descriptor() ([]byte, []int) {
	return file_propu_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta_Propuesta) GetRespuesta() string {
	if x != nil {
		return x.Respuesta
	}
	return ""
}

var File_propu_proto protoreflect.FileDescriptor

var file_propu_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x70, 0x75, 0x22, 0x3c, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x5f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x64, 0x61, 0x12, 0x26, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x22, 0x33, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x5f,
	0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73,
	0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x32, 0x53, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x70, 0x75,
	0x12, 0x4a, 0x0a, 0x0f, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x75, 0x2e, 0x50, 0x72, 0x6f, 0x70,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x5f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x64, 0x61, 0x1a, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x70, 0x75, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61,
	0x5f, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_propu_proto_rawDescOnce sync.Once
	file_propu_proto_rawDescData = file_propu_proto_rawDesc
)

func file_propu_proto_rawDescGZIP() []byte {
	file_propu_proto_rawDescOnce.Do(func() {
		file_propu_proto_rawDescData = protoimpl.X.CompressGZIP(file_propu_proto_rawDescData)
	})
	return file_propu_proto_rawDescData
}

var file_propu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_propu_proto_goTypes = []interface{}{
	(*Propuesta_Generada)(nil),  // 0: propu.Propuesta_Generada
	(*Respuesta_Propuesta)(nil), // 1: propu.Respuesta_Propuesta
}
var file_propu_proto_depIdxs = []int32{
	0, // 0: propu.Propu.EnviarPropuesta:input_type -> propu.Propuesta_Generada
	1, // 1: propu.Propu.EnviarPropuesta:output_type -> propu.Respuesta_Propuesta
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_propu_proto_init() }
func file_propu_proto_init() {
	if File_propu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_propu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Propuesta_Generada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_propu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta_Propuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_propu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_propu_proto_goTypes,
		DependencyIndexes: file_propu_proto_depIdxs,
		MessageInfos:      file_propu_proto_msgTypes,
	}.Build()
	File_propu_proto = out.File
	file_propu_proto_rawDesc = nil
	file_propu_proto_goTypes = nil
	file_propu_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PropuClient is the client API for Propu service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PropuClient interface {
	EnviarPropuesta(ctx context.Context, in *Propuesta_Generada, opts ...grpc.CallOption) (*Respuesta_Propuesta, error)
}

type propuClient struct {
	cc grpc.ClientConnInterface
}

func NewPropuClient(cc grpc.ClientConnInterface) PropuClient {
	return &propuClient{cc}
}

func (c *propuClient) EnviarPropuesta(ctx context.Context, in *Propuesta_Generada, opts ...grpc.CallOption) (*Respuesta_Propuesta, error) {
	out := new(Respuesta_Propuesta)
	err := c.cc.Invoke(ctx, "/propu.Propu/EnviarPropuesta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropuServer is the server API for Propu service.
type PropuServer interface {
	EnviarPropuesta(context.Context, *Propuesta_Generada) (*Respuesta_Propuesta, error)
}

// UnimplementedPropuServer can be embedded to have forward compatible implementations.
type UnimplementedPropuServer struct {
}

func (*UnimplementedPropuServer) EnviarPropuesta(context.Context, *Propuesta_Generada) (*Respuesta_Propuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarPropuesta not implemented")
}

func RegisterPropuServer(s *grpc.Server, srv PropuServer) {
	s.RegisterService(&_Propu_serviceDesc, srv)
}

func _Propu_EnviarPropuesta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Propuesta_Generada)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropuServer).EnviarPropuesta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/propu.Propu/EnviarPropuesta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropuServer).EnviarPropuesta(ctx, req.(*Propuesta_Generada))
	}
	return interceptor(ctx, in, info, handler)
}

var _Propu_serviceDesc = grpc.ServiceDesc{
	ServiceName: "propu.Propu",
	HandlerType: (*PropuServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnviarPropuesta",
			Handler:    _Propu_EnviarPropuesta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "propu.proto",
}
